/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABadgeRibbon: typeof import('ant-design-vue/es')['BadgeRibbon']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatTest: typeof import('./src/components/ChatTest.vue')['default']
    FetchTest: typeof import('./src/components/FetchTest.vue')['default']
    FloatButton: typeof import('./src/components/FloatButton.vue')['default']
    GPTS: typeof import('./src/components/GPTS.vue')['default']
    GPTSCreate: typeof import('./src/components/GPTSCreate.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginLogout: typeof import('./src/components/LoginLogout.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    Payment: typeof import('./src/components/Payment.vue')['default']
    PaySuccess: typeof import('./src/components/PaySuccess.vue')['default']
    PrivacyAgreement: typeof import('./src/components/PrivacyAgreement.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RobotList: typeof import('./src/components/RobotList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchEngine: typeof import('./src/components/SwitchEngine.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter.vue')['default']
    UserAgreement: typeof import('./src/components/UserAgreement.vue')['default']
    WechatLogin: typeof import('./src/components/WechatLogin.vue')['default']
  }
}
