version: '1.0.6'
services:
  chat-with-gpt-frontend:
    container_name: chat-with-gpt-frontend
    image: chat-with-gpt-frontend:${GIT_COMMIT_HASH}
    ports:
      - "80:80"
    volumes:
      - avatars_volume:/usr/share/nginx/html/avatars
      - certbot_certs_volume:/etc/letsencrypt
      - letsencrypt_lib_volume:/var/lib/letsencrypt
      - webroot_volume:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GIT_COMMIT_HASH=${GIT_COMMIT_HASH}

volumes:
  avatars_volume:
    external: true
  certbot_certs_volume:
    external: true
  letsencrypt_lib_volume:
    external: true
  webroot_volume:
    external: true