version: '1.0.6'
services:
  chat-with-gpt-frontend:
    container_name:
      chat-with-gpt-frontend
    image: chat-with-gpt-frontend:${GIT_COMMIT_HASH}
    ports:
      - "8080:80"
    environment:
      - GIT_COMMIT_HASH=${GIT_COMMIT_HASH}